name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  macos-test-build-release-xcode:
    runs-on: macos-11
    strategy:
      matrix:
        xcode: [11.7, 12.5.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode }}.app'
      - name: Test
        run: make test
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      - name: Upload test artifacts
        if: failure()
        uses: actions/upload-artifact@v3.1.1
        with:
          name: test-artifacts-${{ matrix.xcode }}-${{ github.run_id }}
          path: |
            .build/**/*.json
            .build/**/*.xctest
      - name: Build Release
        run: make buildRelease
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      - name: Upload build artifacts
        if: failure()
        uses: actions/upload-artifact@v3.1.1
        with:
          name: build-artifacts-${{ matrix.xcode }}-${{ github.run_id }}
          path: |
            *.lcov
            .build/*.yaml
            .build/**/*.a
            .build/**/*.so
            .build/**/*.dylib
            .build/**/*.dSYM 
            .build/**/*.json
