name: Check markdown links

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Inject GH token into config
      run: sed -i 's/GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN }}/g' .github/workflows/mlc_config.json
    - name: markdown-link-check
      uses: gaurav-nelson/github-action-markdown-link-check@master
      with:
        config-file: '.github/workflows/mlc_config.json'

